services:
  - type: web
    name: dojo-apps
    runtime: node
    plan: free
    region: oregon     # change to your preference later (ohio/frankfurt/etc.)
    repo: https://github.com/illyrianmma/dojo-apps
    branch: main
    buildCommand: npm install
    startCommand: node server.js
    autoDeploy: true
    envVars:
      - key: NODE_ENV
        value: production
      - key: DOJO_DB
        value: /var/data/dojo.db
    disk:
      name: data
      mountPath: /var/data
      sizeGB: 1
